Replace ex admin
ElixirCLE/pairmotron pull request #155
Opened 2017-04-02 20:08 UTC by mbramson

Remove ex admin from the project in favor of standard crud routes. This paves the way to being able to bump phoenix to 1.3, and generally removes a dependency that has given us a number of issues.

2017-04-04 19:26 UTC, ericworkman commented
@mbramson This is a lot to review, so it's going to take me some time. A quick glance and pull-and-run looks good to me, but I'd like to review it in more detail. 👍 for removing exadmin

2017-04-09 00:56 UTC, ericworkman requested changes
Awesome job! Only these couple of things stick out to me.

2017-04-09 00:56 UTC, ericworkman commented on web/controllers/admin/group_membership_request_controller.ex
> +    changeset = GroupMembershipRequest.changeset(%GroupMembershipRequest{}, group_membership_request_params)
This works, but it would probably be better to use `users_changeset`.

2017-04-09 00:56 UTC, ericworkman commented on web/controllers/admin/user_controller.ex
> +    changeset = User.changeset(%User{}, user_params)
I think you should use `registration_changeset` so that the password validation happens.

2017-04-10 02:44 UTC, mbramson commented on web/controllers/admin/user_controller.ex
> +    changeset = User.changeset(%User{}, user_params)
Password validation still happens with the regular changeset. Additionally, using the `registration_changeset` would not allow admins to make other users admins.

2017-04-10 02:45 UTC, mbramson commented on web/controllers/admin/group_membership_request_controller.ex
> +    changeset = GroupMembershipRequest.changeset(%GroupMembershipRequest{}, group_membership_request_params)
Good call!

2017-04-10 13:05 UTC, ericworkman commented on web/controllers/admin/user_controller.ex
> +    changeset = User.changeset(%User{}, user_params)
Good call!

2017-04-10 13:07 UTC, ericworkman requested changes

2017-04-10 13:07 UTC, ericworkman commented on web/controllers/admin/group_membership_request_controller.ex
> +    changeset = GroupMembershipRequest.users_changeset(%GroupMembershipRequest{}, group_membership_request_params)
`users_changeset` requires the third argument of `group`.

2017-04-10 14:04 UTC, mbramson commented on web/controllers/admin/group_membership_request_controller.ex
> +    changeset = GroupMembershipRequest.users_changeset(%GroupMembershipRequest{}, group_membership_request_params)
Doh

2017-04-11 01:56 UTC, mbramson commented
Changes made, let me know what you think!

2017-04-11 13:31 UTC, ericworkman approved these changes

2017-04-11 13:31 UTC, ericworkman commented
Awesome job! Looks good! :shipit:

2017-04-11 13:32 UTC, merged