Add docker support for development and testing
ElixirCLE/pairmotron pull request #161
Opened 2017-06-25 19:36 UTC by devertap

In this pull request, I've added a base elixir image with some minor dependencies.  Then it is wired up using docker-compose in conjunction with a standard postgres:9.5 image.  

I then documented it via the README.  You'll notice I changed the config for the local PG_USER/PASSWORD.  This was to make them the same and accessible via the dev.exs and test.exs.

Hope it helps.

2017-06-26 15:02 UTC, mbramson commented
Hey, thanks for the PR! I'll take a look at this this week. I have a few compatibility concerns since this app is currently deployed to heroku. Also take a look at those CI failures. Tests will have to be passing before this is merged.

2017-06-26 15:33 UTC, Serneum reviewed
You may need to update travis.yml as well since it contains a settings POSTGRES_* variables. I think that's why the tests are failing

2017-06-26 15:33 UTC, Serneum commented on docker-compose.yml
> +    - POSTGRES_USER=postgres
I'm not familiar with docker-compose, but should this be `DB_ENV_POSTGRES_USER` like you had above?

2017-06-26 20:41 UTC, devertap commented on docker-compose.yml
> +    - POSTGRES_USER=postgres
Yeah this is the problem.  It cannot find the environment variables. If we are setting up the variables in test setup then it needs to be DB_ENV_POSTGRES_USER, DB_ENV_POSTGRES_PASSWORD.

2017-06-26 20:50 UTC, devertap commented
Well, it looks like just changing that config wasn't enough.  When I get a little time I will take a look at this a little deeper.

2017-07-02 20:30 UTC, Serneum commented
A `git pull origin master --rebase` is preferred over a merge commit

2017-07-03 17:59 UTC, ericworkman requested changes
Thanks @devertap ! PR looks pretty good, just a couple of minor changes I'd suggest for now!

2017-07-03 17:59 UTC, ericworkman commented on README.md
> +    * docker-compose run -e "MIX_ENV=test" web mix test/controllers/group_controller_test.exs
Typo in `web mix test/controllers/group_controller_test.exs`. Should be `web mix 
test test/controllers/group_controller_test.exs`

2017-07-03 17:59 UTC, ericworkman commented on config/dev.exs
> +  hostname: System.get_env("PG_HOST"),
I suggest `System.get_env("PG_HOST") || "localhost"` for this file and test.exs. That allows for overriding but prevents existing developers from needing another env var.

2017-07-05 20:43 UTC, devertap commented
Closing and reopening in PR #171

2017-07-05 20:43 UTC, closed without merging