Add functionality for activating/deactivating users in the users list
ElixirCLE/pairmotron pull request #27
Opened 2016-11-16 00:51 UTC by Serneum

Closes #25

2016-11-18 14:21 UTC, mbramson requested changes

2016-11-18 14:21 UTC, mbramson commented on test/controllers/user_controller_test.exs
> +  end
I think that these tests are testing too many things at once. You've even left whitespace where these tests should probably be broken out.

2016-11-18 14:21 UTC, mbramson commented on web/controllers/user_controller.ex
> +  end
We should definitely explore ways to accomplish this without adding new non-RESTful controller methods, as discussed.

2016-11-19 19:43 UTC, Serneum commented
@mbramson Commit one isn't RESTful, but cleaner in my opinion. Commit two is the more RESTful but I hate it

2016-12-02 21:14 UTC, daveshah commented on web/router.ex
> +      put "/deactivate", UserController, :deactivate, as: :deactivate
This doesn't seem to follow RESTful type behavior. Why are 'activate' and 'deactivate' their own routes here?

2017-02-03 18:44 UTC, mbramson commented
Closing in favor of https://github.com/ElixirCLE/pairmotron/issues/85, since the /users route no longer exists. That issue is a great opportunity to introduce react into this project.

2017-02-03 18:44 UTC, closed without merging